// Development-only tests; run with Node. The teaching app itself needs no Node.
const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const root=path.join(__dirname,'..');let passed=0;
function test(name,fn){fn();passed++;console.log('PASS '+name);}
function harness(saved,failStorage=false){const elements=new Map(),events={},memory={};if(saved)memory['masters-decision-tree-v1']=JSON.stringify(saved);
 function el(key){if(!elements.has(key))elements.set(key,{innerHTML:'',textContent:'',dataset:{},style:{},disabled:false,open:false,clientWidth:900,clientHeight:520,querySelector(sel){return el(key+' '+sel);},querySelectorAll(){return [];},addEventListener(){},setAttribute(){},getAttribute(){return '700';},focus(){},showModal(){this.open=true;},close(){this.open=false;},scrollIntoView(){},scrollTo(){},matches(){return false;}});return elements.get(key);}
 const document={querySelector:el,querySelectorAll:()=>[],activeElement:null,body:el('body'),addEventListener:(type,fn)=>events[type]=fn};const localStorage={getItem:k=>{if(failStorage)throw Error();return memory[k]||null;},setItem:(k,v)=>{if(failStorage)throw Error();memory[k]=v;},removeItem:k=>delete memory[k]};
 const c={window:{addEventListener(){}},document,localStorage,console,setTimeout,Date,Math,Set,Map,WeakMap,Blob,FormData:class{constructor(form){this.values=form.values;}get(k){return this.values[k]??null;}}};vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(root,'js/model.js'),'utf8'),c);c.DT=c.window.DT;vm.runInContext(fs.readFileSync(path.join(root,'js/tree.js'),'utf8'),c);return {c,el,events,memory,load(){vm.runInContext(fs.readFileSync(path.join(root,'js/app.js'),'utf8'),c);},get state(){return JSON.parse(memory['masters-decision-tree-v1']);},click(action,id){events.click({target:{closest(sel){return sel==='[data-action]'?{dataset:{action,id}}:null;}}});},submit(values={}){const form=el('#dialog form');form.values=values;form.onsubmit({preventDefault(){},target:form});}};
}
// Load tree.js after exposing DT (classic browser window global semantics).
const h=harness();const D=h.c.DT;
const decision=(s,f='f0')=>{const id=D.id();s.nodes[id]={id,type:'decision',factorId:f,branches:[]};return id;};
const branch=(s,n,criterion='Student-written condition',type=null,target=null)=>{const id=D.id();s.branches[id]={id,sourceNodeId:n,criterion,targetType:type,targetId:target};s.nodes[n].branches.push(id);return id;};
const leaf=(s,label='Student-written outcome')=>{const id=D.id();s.leaves[id]={id,label};return id;};
const complete=()=>{const s=D.fresh();s.rootNodeId=decision(s);branch(s,s.rootNodeId,'Condition A','leaf',leaf(s));branch(s,s.rootNodeId,'Condition B','leaf',leaf(s));return s;};
test('A: provided factors only; unused factors permitted',()=>{const s=complete();assert.equal(D.validate(s).length,0);assert.equal(s.customFactors.length,0);});
test('B/C: three custom factors, edits, deletion, empty factor validation',()=>{h.load();for(let i=0;i<4;i++)h.click('add-custom');assert.equal(h.state.customFactors.length,3);assert(D.validate(h.state).some(x=>x.includes('empty')));const id=h.state.customFactors[0].id;h.click('delete-custom',id);h.submit();assert.equal(h.state.customFactors.length,2);h.el('#undo').onclick();assert.equal(h.state.customFactors.length,3);h.el('#redo').onclick();assert.equal(h.state.customFactors.length,2);});
test('D: root change retains branches; undo/redo preserve logic',()=>{const x=harness(complete());x.load();x.el('#continue').onclick();const before=x.c.DT.clone(complete());x.click('root','f1');x.submit();const current=x.state;assert.equal(current.nodes[current.rootNodeId].factorId,'f1');assert.equal(Object.keys(current.branches).length,2);x.el('#undo').onclick();assert.equal(x.state.nodes[x.state.rootNodeId].factorId,'f0');x.el('#redo').onclick();assert.equal(x.state.nodes[x.state.rootNodeId].factorId,'f1');});
test('E/F: >2 branches supported; missing criterion and target independently reported',()=>{const s=complete();branch(s,s.rootNodeId,'');const issues=D.validate(s);assert(issues.some(x=>x.includes('criterion')));assert(issues.some(x=>x.includes('does not yet connect')));assert(!issues.some(x=>x.includes('fewer than two')));});
test('G: subtree deletion leaves no orphan objects and can be undone',()=>{const s=complete(),child=decision(s);const bid=branch(s,s.rootNodeId,'Condition C','decision',child);branch(s,child,'Condition D','leaf',leaf(s));const x=harness(s);x.load();x.el('#continue').onclick();x.click('delete-node',child);x.submit();assert(!x.state.nodes[child]);assert.equal(Object.keys(x.state.leaves).length,2);assert.equal(x.state.branches[bid].targetId,null);assert(!D.validate(x.state).some(x=>x.includes('disconnected')));x.el('#undo').onclick();assert(x.state.nodes[child]);});
test('H: storage restore, cancellation of new tree, and unavailable storage',()=>{const s=complete(),x=harness(s);x.load();assert(x.el('#dialog').innerHTML.includes('Continue your previous'));x.el('#start-new').onclick();x.el('#dialog [data-close]').onclick();x.click('root','f2');x.submit();assert.equal(Object.keys(x.state.branches).length,2);const y=harness(null,true);assert.doesNotThrow(()=>y.load());assert(y.el('#save-status').textContent.includes('unavailable'));});
test('I: JSON round trip and standalone SVG escaping',()=>{const s=complete();Object.values(s.leaves)[0].label='<script>& "test"';assert.equal(D.validate(JSON.parse(JSON.stringify(s))).length,0);const svg=D.tree(s).svg;assert(svg.includes('&lt;script&gt;'));assert(!svg.includes('<script>'));assert(svg.includes('xmlns="http://www.w3.org/2000/svg"'));fs.writeFileSync('/tmp/decision-tree-test.svg',svg);});
test('J: 15 decision nodes, 16 leaves, 30 branches; layout without node overlap',()=>{const s=D.fresh();function grow(depth){const id=decision(s,'f'+(depth%5));for(let i=0;i<2;i++)branch(s,id,'Student condition '+i,depth<3?'decision':'leaf',depth<3?grow(depth+1):leaf(s,'A long student-defined outcome that wraps over several lines'));return id;}s.rootNodeId=grow(0);assert.equal(Object.keys(s.nodes).length,15);assert.equal(Object.keys(s.leaves).length,16);assert.equal(D.validate(s).length,0);const t=D.tree(s);const boxes=[...t.svg.matchAll(/<g[^>]*><rect x="([\d.]+)" y="([\d.]+)" width="([\d.]+)" height="([\d.]+)"/g)].map(m=>m.slice(1).map(Number));assert.equal(boxes.length,31);for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const [x,y,w,hh]=boxes[i],[a,b,c,d]=boxes[j];assert(x+w<=a||a+c<=x||y+hh<=b||b+d<=y,'overlapping nodes');}fs.writeFileSync('/tmp/decision-tree-large.svg',t.svg);});
test('K: deliberate reuse remains structurally valid',()=>{const s=complete(),id=decision(s,'f0');branch(s,s.rootNodeId,'Condition C','decision',id);branch(s,id,'Condition D','leaf',leaf(s));branch(s,id,'Condition E','leaf',leaf(s));assert.equal(D.validate(s).length,0);});
test('L: moves prevent cycles, preserve descendants, and expose original incomplete route',()=>{const s=complete(),id=decision(s),incoming=branch(s,s.rootNodeId,'Condition C','decision',id),self=branch(s,id,'Condition D'),destination=branch(s,s.rootNodeId,'Condition E');assert.throws(()=>D.move(s,id,self),/ancestor/);D.move(s,id,destination);assert.equal(s.branches[incoming].targetId,null);assert.equal(s.branches[destination].targetId,id);assert(!D.validate(s).some(x=>x.includes('disconnected')));branch(s,id,'Cycle','decision',s.rootNodeId);assert(D.validate(s).some(x=>x.includes('cycle')));assert.throws(()=>D.checkSaved(s));});
test('M: keyboard alternatives, native dialogs and labels exist (source audit)',()=>{const source=fs.readFileSync(path.join(root,'js/app.js'),'utf8');assert(source.includes('keyboard editing'));assert(source.includes("e.key==='Enter'"));assert(source.includes('showModal()'));assert(source.includes('aria-label'));assert(source.includes('Move node'));});
test('UI handlers: add/edit branch, create leaf, reorder, delete, validate',()=>{const x=harness(complete());x.load();x.el('#continue').onclick();const rootId=JSON.parse(x.memory['masters-decision-tree-v1']).rootNodeId;x.click('add-branch',rootId);x.submit({criterion:'My category'});const bid=x.state.nodes[rootId].branches[2];x.click('edit-branch',bid);x.submit({criterion:'Revised condition'});assert.equal(x.state.branches[bid].criterion,'Revised condition');x.click('next-target',bid);x.submit({kind:'leaf',outcome:'My outcome'});assert.equal(D.validate(x.state).length,0);x.click('up',bid);assert.equal(x.state.nodes[rootId].branches[1],bid);x.click('delete-branch',bid);x.submit();assert.equal(Object.keys(x.state.leaves).length,2);x.el('#check').onclick();assert(x.el('#validation').innerHTML.includes('Structurally complete'));});
test('Empty leaf, disconnected objects, and corrupt saved state are detected',()=>{const s=complete();Object.values(s.leaves)[0].label=' ';assert(D.validate(s).some(x=>x.includes('needs a label')));decision(s);assert(D.validate(s).some(x=>x.includes('disconnected')));assert.throws(()=>D.checkSaved(s));});
test('Custom factor typing and reflection responses persist and undo as field edits',()=>{const x=harness();x.load();x.click('add-custom');const id=x.state.customFactors[0].id;const input={dataset:{custom:id},value:'My factor',matches:sel=>sel.includes('[data-custom]')};x.events.focusin({target:input});x.events.input({target:input});x.events.change({target:input});assert.equal(x.state.customFactors[0].label,'My factor');x.el('#undo').onclick();assert.equal(x.state.customFactors[0].label,'');x.el('#redo').onclick();assert.equal(x.state.customFactors[0].label,'My factor');const response={dataset:{reflection:'0'},value:'My reasoning',matches:sel=>sel.includes('[data-reflection]')};x.events.focusin({target:response});x.events.input({target:response});x.events.change({target:response});assert.equal(x.state.reflections[0],'My reasoning');});
test('History retains exactly the last 20 meaningful actions',()=>{const x=harness(complete());x.load();x.el('#continue').onclick();const id=JSON.parse(x.memory['masters-decision-tree-v1']).rootNodeId;for(let i=0;i<25;i++){x.click('add-branch',id);x.submit({criterion:'Condition '+i});}for(let i=0;i<25;i++)x.el('#undo').onclick();assert.equal(Object.keys(x.state.branches).length,7);assert.equal(x.el('#undo').disabled,true);});
test('Wide glyphs and Unicode labels wrap without dropping content',()=>{const s=complete();Object.values(s.leaves)[0].label='W'.repeat(240);const svg=D.tree(s).svg;assert(!svg.includes('W'.repeat(15)));assert.equal((svg.match(/W/g)||[]).length,240);});
console.log(`${passed} test groups passed. DOM shim tests state/event handlers; they do not substitute for browser interaction tests.`);
(async()=>{
 const x=harness(),s=complete(),captured=[];vm.runInContext(fs.readFileSync(path.join(root,'js/export.js'),'utf8'),x.c);x.c.DT.download=(blob,name)=>captured.push({blob,name});x.c.window.print=()=>{x.printed=true;};
 await x.c.DT.exportFile(s,'json');assert.equal(JSON.parse(await captured[0].blob.text()).rootNodeId,s.rootNodeId);
 await x.c.DT.exportFile(s,'svg');assert((await captured[1].blob.text()).includes('<svg'));
 s.reflections[0]='Student response < &';await x.c.DT.exportFile(s,'print');assert(x.printed);assert(x.el('#print-view').innerHTML.includes('Student response &lt; &amp;'));assert(x.el('#print-view').innerHTML.includes('Generated'));
 console.log('PASS export handlers: downloadable JSON/SVG blobs and complete print content');
})().catch(err=>{console.error(err);process.exitCode=1;});
